<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Generate 50 employees assigned to the 5 pre-created departments

        // Employee::create([
        //     'employee_number' => 'PS-TECH-2039',
        //     'access_card_number' => 'PS-4093',
        //     'first_name' => 'Korkoe',
        //     'other_name' => 'Anthony Kwami',
        //     'last_name' => 'Dumashie',
        //     'email' => 'korkoedumashie@gmail.com',
        //     'phone_number' => '233558731186',
        //     'department_id' => 2,
        //     'job_title' => 'Software Engineer',
        //     'gender' => 'male',
        // ]);

        $employees = [
            [
                'first_name' => 'NATHAN',
                'other_name' => 'LEE-WINANS',
                'last_name' => 'ANNOBI',
                'email' => 'nannobi@payswitch.com.gh',
                'department_id' => 1,
                'job_title' => 'Board Chairman',
                'gender' => 'male',
            ],
            [
                'first_name' => 'EMMANUEL',
                'other_name' => '',
                'last_name' => 'SACKEY-KYERE',
                'email' => 'esackey-kyere@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'MOBILE DEVELOPER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'SALIU',
                'other_name' => 'JULIEN',
                'last_name' => 'OKYERE',
                'email' => 'sokyere@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'Chief Technology Officer',
                'gender' => 'male',
            ],
            [
                'first_name' => 'NAOMI',
                'other_name' => '',
                'last_name' => 'ANANE',
                'email' => 'nanane@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'HEAD OF BUSINESS',
                'gender' => 'female',
            ],
            [
                'first_name' => 'THEODORA',
                'other_name' => 'AMA',
                'last_name' => 'MOSES',
                'email' => 'tmoses@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'HEAD OF BUSINESS',
                'gender' => 'female',
            ],
            [
                'first_name' => 'AARON',
                'other_name' => '',
                'last_name' => 'DEMENU',
                'email' => 'ademenu@payswitch.com.gh',
                'department_id' => 1,
                'job_title' => 'Chief Executive Officer',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ABIGAIL',
                'other_name' => 'KORANTENG',
                'last_name' => 'ATTAH',
                'email' => 'akoranteng@payswitch.com.gh',
                'department_id' => 4,
                'job_title' => 'HR & ADMIN OFFICER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'EMMANUEL',
                'other_name' => 'BENONI',
                'last_name' => 'NARH',
                'email' => 'enarh@payswitch.com.gh',
                'department_id' => 6,
                'job_title' => 'CHIEF COMPLIANCE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'PEGGY',
                'other_name' => 'ADOBEA',
                'last_name' => 'OTTOPA-KISIEDU',
                'email' => 'pottopa-kisiedu@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS SUPPORT OFFICER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'BISMARK',
                'other_name' => 'AMO',
                'last_name' => 'ABBEW',
                'email' => 'baamo@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'MOBILE DEVELOPER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'CHRISTIAN',
                'other_name' => '',
                'last_name' => 'ASHLEY',
                'email' => 'cashley@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'UI/UX DESIGNER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'JOSEPH',
                'other_name' => 'BOATENG',
                'last_name' => 'OKYERE',
                'email' => 'jbokyere@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'FULL STACK DEVELOPER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'NANA',
                'other_name' => 'DANQUAH',
                'last_name' => 'OBENG-AMOAKO',
                'email' => 'nobeng-amoako@payswitch.com.gh',
                'department_id' => 8,
                'job_title' => 'INFORMATION SECURITY MANAGER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'DAVID',
                'other_name' => '',
                'last_name' => 'ANSAH',
                'email' => 'dansah@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS DEVELOPMENT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ISAAC',
                'other_name' => 'KOMLA',
                'last_name' => 'DZATHOR',
                'email' => 'idzathor@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'TERMINALS & OPERATIONS SUPPORT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'MABEL',
                'other_name' => '',
                'last_name' => 'TETTEH',
                'email' => 'mtetteh@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS SUPPORT OFFICER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'BENJAMIN',
                'other_name' => 'BUAH',
                'last_name' => 'ANDOH',
                'email' => 'bandoh@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS DEVELOPMENT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'KELLY',
                'other_name' => 'KWAME',
                'last_name' => 'CORCHIL',
                'email' => 'kcorchil@payswitch.com.gh',
                'department_id' => 9,
                'job_title' => 'HEAD, PROJECTS & PRODUCTS',
                'gender' => 'male',
            ],
            [
                'first_name' => 'JUDITH',
                'other_name' => 'EMEFA',
                'last_name' => 'NYARKO',
                'email' => 'jenyarko@payswitch.com.gh',
                'department_id' => 7,
                'job_title' => 'CYBER SECURITY OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ERNEST',
                'other_name' => 'KODWO',
                'last_name' => 'MENSAH',
                'email' => 'ekmensah@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'HEAD OF TECH SUPPORT & SERVICES',
                'gender' => 'male',
            ],
            [
                'first_name' => 'SLANSET',
                'other_name' => 'SEFAKOR',
                'last_name' => 'AMEDUME',
                'email' => 'samedome@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS DEVELOPMENT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'PRINCE',
                'other_name' => '',
                'last_name' => 'ANTWI',
                'email' => 'pantwi@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'NETWORK & INFRASTRUCTURE SUPERVISOR',
                'gender' => 'male',
            ],
            [
                'first_name' => 'SHERIFF',
                'other_name' => 'ATTIKU',
                'last_name' => 'MOHAMMED',
                'email' => 'smohammed@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'NETWORK & INFRASTRUCTURE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'MAXWELL',
                'other_name' => '',
                'last_name' => 'ARMAH',
                'email' => 'marmah@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'FRONT END DEVELOPER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ERNEST',
                'other_name' => 'JUNIOR',
                'last_name' => 'AWUKU',
                'email' => 'eawuku@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'FRONT END DEVELOPER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'MORDECAI',
                'other_name' => 'TETTEH',
                'last_name' => 'ADDO',
                'email' => 'maddo@payswitch.com.gh',
                'department_id' => 3,
                'job_title' => 'BUSINESS DEVELOPMENT OFFICER- SUPPORT',
                'gender' => 'male',
            ],
            [
                'first_name' => 'AUSTIN',
                'other_name' => 'MAWULI',
                'last_name' => 'ADEGAH',
                'email' => 'amadegah@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'NETWORK & INFRASTRUCTURE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'SYLVESTER',
                'other_name' => '',
                'last_name' => 'ARTHUR',
                'email' => 'sarthur@payswitch.com.gh',
                'department_id' => 9,
                'job_title' => 'PROJECT & PRODUCT OFFICER(INNOVATIONS & DATA ANALYSIS',
                'gender' => 'male',
            ],
            [
                'first_name' => 'LETICIA',
                'other_name' => 'AGYEI',
                'last_name' => 'FRIMPONG',
                'email' => 'lafrimpong@payswitch.com.gh',
                'department_id' => 9,
                'job_title' => 'PROJECT & PRODUCT OFFICER(PROJECTS & PARTNERSHIPS',
                'gender' => 'female',
            ],
            [
                'first_name' => 'KORKOE',
                'other_name' => 'ANTHONY KWAMI',
                'last_name' => 'DUMASHIE',
                'email' => 'kdumashie@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'SOFTWARE ENGINEER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'MICHAEL',
                'other_name' => '',
                'last_name' => 'APPIAH',
                'email' => 'mappiah@payswitch.com.gh',
                'department_id' => 6,
                'job_title' => 'AUDIT & COMPLIANCE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ABIGAIL',
                'other_name' => '',
                'last_name' => 'ADDAI-MENSAH',
                'email' => 'aaddai-mensah@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNT OFFICER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'ABIGAIL',
                'other_name' => 'AMA',
                'last_name' => 'AMOH',
                'email' => 'aamoh@payswitch.com.gh',
                'department_id' => 4,
                'job_title' => 'HEAD, HR & FACILITIES',
                'gender' => 'male',
            ],
            [
                'first_name' => 'KENNEDY',
                'other_name' => '',
                'last_name' => 'AKAKPO',
                'email' => 'kakakpo@payswitch.com.gh',
                'department_id' => 7,
                'job_title' => 'CHIEF OPERATING OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'SOLOMON',
                'other_name' => '',
                'last_name' => 'DANIELS',
                'email' => 'sdaniels@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNTANT',
                'gender' => 'male',
            ],
            [
                'first_name' => 'PHILIP',
                'other_name' => '',
                'last_name' => 'ATSU-MENSAH',
                'email' => 'pamensah@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'PRINCE',
                'other_name' => 'HENRY',
                'last_name' => 'AMEMOR',
                'email' => 'pamemor@payswitch.com.gh',
                'department_id' => 6,
                'job_title' => 'AUDIT & COMPLIANCE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'DAVID',
                'other_name' => '',
                'last_name' => 'NGBAM',
                'email' => 'dngbam@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'DANIEL',
                'other_name' => 'TAKYI',
                'last_name' => 'QUANSAH',
                'email' => 'dtquansah@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'TECHNICAL SUPPORT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'JOANA',
                'other_name' => 'DELALI AFI',
                'last_name' => 'AWUITOR',
                'email' => '',
                'department_id' => 9,
                'job_title' => 'SOCIAL MEDIA MARKETER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'Isaac',
                'other_name' => '',
                'last_name' => 'Aboagye',
                'email' => 'ioaboagye@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'NATIONAL SERVICE PERSONNEL',
                'gender' => 'male',
            ],
            [
                'first_name' => 'RAYMOND',
                'other_name' => 'TEYETTEY',
                'last_name' => 'BORKOR',
                'email' => 'rtborkor@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'SOFTWARE ENGINEER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'JESSE',
                'other_name' => 'JACKSON SEFA',
                'last_name' => 'MANU',
                'email' => 'jjsefa@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'SOFTWARE ENGINEER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'EMMANUEL',
                'other_name' => '',
                'last_name' => 'ARHIN',
                'email' => 'earhin@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'SOFTWARE ENGINEER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'MARVIN',
                'other_name' => 'KING',
                'last_name' => 'KABUTEY',
                'email' => 'mkkabutey@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'TECHNICAL SUPPORT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'TIMOTHY',
                'other_name' => '',
                'last_name' => 'AYEKE',
                'email' => 'tayeke@payswitch.com.gh',
                'department_id' => 2,
                'job_title' => 'TECHNICAL SUPPORT OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'ERIC',
                'other_name' => '',
                'last_name' => 'DORGBLEY',
                'email' => 'edorgbley@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNTANT',
                'gender' => 'male',
            ],
            [
                'first_name' => 'EVELYN',
                'other_name' => '',
                'last_name' => 'AHADZI',
                'email' => 'eahadzi@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'ACCOUNT OFFICER',
                'gender' => 'female',
            ],
            [
                'first_name' => 'DAVID',
                'other_name' => '',
                'last_name' => 'ASIEDU',
                'email' => 'dasiedu@payswitch.com.gh',
                'department_id' => 5,
                'job_title' => 'CHIEF FINANCE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'DAVID',
                'other_name' => 'ADJAH',
                'last_name' => 'BOTCHWAY',
                'email' => 'dabotchway@payswitch.com.gh',
                'department_id' => 6,
                'job_title' => 'AUDIT & COMPLIANCE OFFICER',
                'gender' => 'male',
            ],
            [
                'first_name' => 'BUKARI',
                'other_name' => '',
                'last_name' => 'AHEVI',
                'email' => 'biahevi@payswitch.com.gh',
                'department_id' => 6,
                'job_title' => 'AUDIT & COMPLIANCE OFFICER',
                'gender' => 'male',
            ],
        ];        // Employee::factory()->count(10)->create();

                foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}
